//Module for create a simple mongo database

const mongoose = require('mongoose');


//Schema
//This schema will have short url id which is generated by the server and the original id which is given by the user
const urlSchema = new mongoose.Schema({
    shortid: {
        type: String,
        unique: true,
        required: true
    },
    originalUrl: {
        type: String,
        required: true
    },
    visit: [{timestamps: {type: Number}}],
}, {timestamps: true});


//Model
const urlModel = mongoose.model('url', urlSchema);

//exporting module
module.exports = urlModel;